"""empty message

Revision ID: 53c9c429122a
Revises: None
Create Date: 2015-08-22 22:30:38.855000

"""

# revision identifiers, used by Alembic.
revision = '53c9c429122a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=True),
    sa.Column('definition', sa.String(length=140), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    ### end Alembic commands ###
